### ISSUE TITLE
Torch version 1.10.2

### ISSUE THREAD

**Issue by VladimirVincan** [Serbian-AI-Society/SrbAI#11]
When trying to install SrbAI via the command `python -m pip install --upgrade build .` the following error occurs:
 `
Collecting build
  Using cached build-0.10.0-py3-none-any.whl (17 kB)
ERROR: Could not find a version that satisfies the requirement torch==1.10.2 (from srbai) (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==1.10.2
`
The solution is to change the following line in `setup.py`:
https://github.com/Serbian-AI-Society/SrbAI/blob/3ca492b3522d48e48dc677595213a5ba6e93eb6d/setup.py#L26
with:
`        "torch>=1.10.2",
`

**Comment by nikolamilosevic86** [comment]
This is fixed with the following pull request: https://github.com/Serbian-AI-Society/SrbAI/pull/12
